import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

const API = '/api'
const formatAge = value => {
  const minutes = Math.max(1, Math.round(Math.abs(new Date(value).getTime() - Date.now()) / 60000))
  if (minutes < 60) return `${minutes} min`
  const hours = Math.floor(minutes / 60); return `${hours}h ${minutes % 60}m`
}
const timeLabel = ticket => ticket.overdue ? `${formatAge(ticket.slaDeadline)} late` : `Due in ${formatAge(ticket.slaDeadline)}`
const initials = name => name?.split(' ').map(part => part[0]).join('').slice(0, 2) || 'UN'

function App() {
  const [stats, setStats] = useState(null); const [data, setData] = useState(null); const [agents, setAgents] = useState([])
  const [filters, setFilters] = useState({ search: '', status: 'all', priority: 'all', assignee: 'all', overdue: false, dueSoon: false, page: 1 })
  const [selected, setSelected] = useState(null); const [creating, setCreating] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const [toast, setToast] = useState('')
  const query = new URLSearchParams({ page: filters.page, limit: 8, search: filters.search, status: filters.status, priority: filters.priority, assignee: filters.assignee, overdue: filters.overdue ? 'true' : '', dueSoon: filters.dueSoon ? 'true' : '' })

  const load = async () => {
    setLoading(true); setError('')
    try {
      const [ticketResponse, statsResponse] = await Promise.all([fetch(`${API}/tickets?${query}`), fetch(`${API}/dashboard/stats`)]); const tickets = await ticketResponse.json(); const nextStats = await statsResponse.json()
      if (!ticketResponse.ok) throw new Error(tickets.error || 'Unable to load queue')
      setData(tickets); setAgents(tickets.agents || []); setStats(nextStats)
    } catch (err) { setError(err.message) } finally { setLoading(false) }
  }
  useEffect(() => { load() }, [filters.search, filters.status, filters.priority, filters.assignee, filters.overdue, filters.dueSoon, filters.page])
  useEffect(() => { const timer = setInterval(load, 60000); return () => clearInterval(timer) }, [filters])
  const updateFilter = (key, value) => setFilters(current => ({ ...current, [key]: value, page: key === 'page' ? value : 1 }))
  const shortcut = (key, value) => setFilters(current => ({ ...current, status: 'all', overdue: false, dueSoon: false, assignee: 'all', [key]: value, page: 1 }))
  const saveTicket = async (id, changes) => { try { const response = await fetch(`${API}/tickets/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(changes) }); if (!response.ok) throw new Error((await response.json()).error); setToast('Ticket updated'); setSelected(null); await load() } catch (err) { setToast(err.message) } }

  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">Q</span><span>QueuePilot</span></div><div className="workspace-label">WORKSPACE</div><button className="nav-item active"><span>▦</span> Smart queue</button><button className="nav-item" onClick={() => shortcut('status', 'Resolved')}><span>✓</span> Resolved archive</button><div className="sidebar-foot"><div className="agent-card"><span className="avatar priya">PS</span><div><strong>Priya Shah</strong><small>Helpdesk lead</small></div><span className="online-dot" /></div></div></aside>
    <main className="main-content"><header className="topbar"><div><div className="eyebrow">Wednesday, September 16, 2026</div><h1>Good morning, Priya</h1></div><button className="new-ticket" onClick={() => setCreating(true)}>+ New ticket</button></header>
      <section className="stats-grid">{[['totalOpen', 'Open tickets', 'All active queue', 'open'], ['overdue', 'Overdue', 'Need attention now', 'overdue'], ['dueSoon', 'Due soon', 'Next 2 hours', 'soon'], ['myTickets', 'My tickets', 'Assigned to Priya', 'mine'], ['resolvedToday', 'Resolved today', 'Closed since midnight', 'resolved']].map(([key, label, sub, tone]) => <button className={`stat-card ${tone}`} key={key} onClick={() => key === 'overdue' ? shortcut('overdue', true) : key === 'dueSoon' ? shortcut('dueSoon', true) : key === 'myTickets' ? shortcut('assignee', String(agents.find(agent => agent.name === 'Priya')?.id || '')) : key === 'resolvedToday' ? shortcut('status', 'Resolved') : shortcut('status', 'all')}><span className="stat-label">{label}</span><strong>{stats?.[key] ?? '—'}</strong><span className="stat-sub">{sub} <span>→</span></span></button>)}</section>
      <section className="queue-heading"><div><div className="eyebrow accent">LIVE PRIORITY QUEUE</div><h2>Smart queue <span className="count-pill">{data?.total ?? 0}</span></h2><p>Tickets are ordered by SLA risk, urgency, and age.</p></div><div className="refresh-label"><span className="pulse" /> Updates every minute</div></section>
      <section className="toolbar"><div className="search-box"><span>⌕</span><input value={filters.search} onChange={event => updateFilter('search', event.target.value)} placeholder="Search tickets, customers..." /></div><select value={filters.status} onChange={event => updateFilter('status', event.target.value)}><option value="all">All statuses</option>{['Open', 'In Progress', 'Waiting'].map(item => <option key={item}>{item}</option>)}</select><select value={filters.priority} onChange={event => updateFilter('priority', event.target.value)}><option value="all">All priorities</option>{['Critical', 'High', 'Medium', 'Low'].map(item => <option key={item}>{item}</option>)}</select><select value={filters.assignee} onChange={event => updateFilter('assignee', event.target.value)}><option value="all">All assignees</option><option value="unassigned">Unassigned</option>{agents.map(agent => <option value={agent.id} key={agent.id}>{agent.name}</option>)}</select><button className={`filter-toggle ${filters.overdue ? 'selected' : ''}`} onClick={() => updateFilter('overdue', !filters.overdue)}>Overdue</button><button className={`filter-toggle ${filters.dueSoon ? 'selected' : ''}`} onClick={() => updateFilter('dueSoon', !filters.dueSoon)}>Due soon</button></section>
      {error && <div className="error-banner">{error}<button onClick={load}>Retry</button></div>}
      {loading ? <div className="loading-list">{[1, 2, 3, 4].map(item => <div className="skeleton" key={item} />)}</div> : data?.items.length ? <div className="ticket-list">{data.items.map((ticket, index) => <TicketRow key={ticket.id} ticket={ticket} rank={(data.page - 1) * data.limit + index + 1} onOpen={() => setSelected(ticket.id)} />)}</div> : <div className="empty-state"><div className="empty-icon">⌕</div><h3>No tickets match these filters</h3><p>Try clearing a filter or searching for another customer.</p><button onClick={() => setFilters({ search: '', status: 'all', priority: 'all', assignee: 'all', overdue: false, dueSoon: false, page: 1 })}>Clear filters</button></div>}
      {data && data.total > 0 && <div className="pagination"><span>Showing {Math.min((data.page - 1) * data.limit + 1, data.total)}–{Math.min(data.page * data.limit, data.total)} of {data.total}</span><div><button disabled={data.page <= 1} onClick={() => updateFilter('page', data.page - 1)}>←</button><span className="page-number">{data.page} / {data.totalPages}</span><button disabled={data.page >= data.totalPages} onClick={() => updateFilter('page', data.page + 1)}>→</button></div></div>}
    </main>
    {selected && <DetailDrawer id={selected} agents={agents} onClose={() => setSelected(null)} onSave={saveTicket} />}
    {creating && <CreateTicket agents={agents} onClose={() => setCreating(false)} onCreated={() => { setCreating(false); setToast('Ticket created'); load() }} />}
    {toast && <button className="toast" onClick={() => setToast('')}>{toast} ×</button>}
  </div>
}

function TicketRow({ ticket, rank, onOpen }) { const [why, setWhy] = useState(false); return <article className={`ticket-row ${rank === 1 ? 'first-ticket' : ''} ${ticket.overdue ? 'is-overdue' : ticket.dueSoon ? 'is-soon' : ''}`}><div className="rank">{String(rank).padStart(2, '0')}</div><div className="ticket-main" onClick={onOpen}><div className="ticket-meta"><span className={`priority-dot ${ticket.priority.toLowerCase()}`} /> <span className={`priority-text ${ticket.priority.toLowerCase()}`}>{ticket.priority}</span><span className="ticket-id">{ticket.ticketNumber}</span><span className={`status status-${ticket.status.toLowerCase().replace(' ', '-')}`}>{ticket.status}</span></div><h3>{ticket.title}</h3><p>{ticket.description}</p><div className="ticket-footer"><span className="customer"><span className="avatar small">{initials(ticket.customerName)}</span>{ticket.customerName}</span><span className="assignee">{ticket.assignee ? <><span className="avatar tiny">{initials(ticket.assignee.name)}</span>{ticket.assignee.name}</> : <span className="unassigned">Unassigned</span>}</span><span className="created">Created {formatAge(ticket.createdAt)} ago</span></div></div><div className="sla-block"><span className={`sla-label ${ticket.overdue ? 'late' : ticket.dueSoon ? 'soon' : ''}`}>{ticket.overdue ? 'OVERDUE' : ticket.dueSoon ? 'DUE SOON' : 'SLA DEADLINE'}</span><strong>{timeLabel(ticket)}</strong><small>{new Date(ticket.slaDeadline).toLocaleString([], { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })}</small></div><button className={`why-button ${why ? 'open' : ''}`} onClick={() => setWhy(!why)}>Why first? <span>{why ? '−' : '+'}</span></button>{why && <div className="why-panel"><strong>Why first?</strong><span>✓ {ticket.overdue ? 'Overdue' : `${ticket.priority} priority`}</span><span>✓ {ticket.overdue ? `${formatAge(ticket.slaDeadline)} past SLA` : `SLA expires in ${formatAge(ticket.slaDeadline)}`}</span><span>→ Ranked #{rank} in the active queue</span></div>}</article> }

function DetailDrawer({ id, agents, onClose, onSave }) { const [ticket, setTicket] = useState(null); const [saving, setSaving] = useState(false); useEffect(() => { fetch(`${API}/tickets/${id}`).then(response => response.json()).then(setTicket) }, [id]); if (!ticket) return <div className="drawer-backdrop"><aside className="drawer"><div className="drawer-loading">Loading ticket...</div></aside></div>; const save = async changes => { setSaving(true); await onSave(ticket.id, changes); setSaving(false) }; return <div className="drawer-backdrop" onClick={onClose}><aside className="drawer" onClick={event => event.stopPropagation()}><div className="drawer-header"><div><span className="ticket-id">{ticket.ticketNumber}</span><h2>{ticket.title}</h2></div><button className="close-button" onClick={onClose}>×</button></div><div className="drawer-sla"><span className={ticket.overdue ? 'late' : 'soon'}>{ticket.overdue ? 'OVERDUE' : 'SLA STATUS'}</span><strong>{timeLabel(ticket)}</strong><small>Deadline {new Date(ticket.slaDeadline).toLocaleString()}</small></div><p className="drawer-description">{ticket.description}</p><div className="detail-fields"><label>Status<select value={ticket.status} disabled={saving} onChange={event => save({ status: event.target.value })}>{['Open', 'In Progress', 'Waiting', 'Resolved'].map(value => <option key={value}>{value}</option>)}</select></label><label>Priority<select value={ticket.priority} disabled={saving} onChange={event => save({ priority: event.target.value })}>{['Critical', 'High', 'Medium', 'Low'].map(value => <option key={value}>{value}</option>)}</select></label><label>Assignee<select value={ticket.assignee?.id || ''} disabled={saving} onChange={event => save({ assigneeId: event.target.value || null })}><option value="">Unassigned</option>{agents.map(agent => <option value={agent.id} key={agent.id}>{agent.name}</option>)}</select></label></div><div className="customer-detail"><span className="avatar">{initials(ticket.customerName)}</span><div><strong>{ticket.customerName}</strong><a href={`mailto:${ticket.customerEmail}`}>{ticket.customerEmail}</a></div></div><div className="activity"><h3>Activity</h3>{ticket.activity?.map(item => <div className="activity-item" key={item.id}><span className="activity-dot" /><div><strong>{item.message}</strong><small>{new Date(item.createdAt).toLocaleString()}</small></div></div>)}</div></aside></div> }

function CreateTicket({ agents, onClose, onCreated }) { const [form, setForm] = useState({ customerName: '', customerEmail: '', title: '', description: '', priority: 'Medium', assigneeId: '' }); const [error, setError] = useState(''); const update = (key, value) => setForm(current => ({ ...current, [key]: value })); const submit = async event => { event.preventDefault(); const response = await fetch(`${API}/tickets`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, assigneeId: form.assigneeId || null }) }); if (!response.ok) { setError((await response.json()).error); return } onCreated() }; return <div className="drawer-backdrop" onClick={onClose}><aside className="drawer" onClick={event => event.stopPropagation()}><div className="drawer-header"><div><div className="eyebrow accent">NEW REQUEST</div><h2>Create a ticket</h2></div><button className="close-button" onClick={onClose}>×</button></div>{error && <div className="error-banner">{error}</div>}<form className="create-form" onSubmit={submit}>{[['customerName', 'Customer name', 'Maya Chen'], ['customerEmail', 'Customer email', 'maya@company.com'], ['title', 'Issue title', 'What needs help?']].map(([key, label, placeholder]) => <label key={key}>{label}<input required value={form[key]} placeholder={placeholder} onChange={event => update(key, event.target.value)} /></label>)}<label>Description<textarea required rows="5" value={form.description} onChange={event => update('description', event.target.value)} /></label><div className="form-row"><label>Priority<select value={form.priority} onChange={event => update('priority', event.target.value)}>{['Critical', 'High', 'Medium', 'Low'].map(value => <option key={value}>{value}</option>)}</select></label><label>Assignee<select value={form.assigneeId} onChange={event => update('assigneeId', event.target.value)}><option value="">Unassigned</option>{agents.map(agent => <option value={agent.id} key={agent.id}>{agent.name}</option>)}</select></label></div><button className="submit-ticket" type="submit">Create ticket</button></form></aside></div> }

createRoot(document.getElementById('root')).render(<App />)